export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_FAILURE = 'FETCH_POKEMON_FAILURE';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SET_MULTIPLE_FILTERS = 'SET_MULTIPLE_FILTERS';
export const SHOW_ALL_POKEMONS = 'SHOW_ALL_POKEMONS';
