export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_FAILURE = 'FETCH_POKEMONS_FAILURE';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SET_MULTIPLE_FILTERS = 'SET_MULTIPLE_FILTERS';
export const SHOW_ALL_POKEMONS = 'SHOW_ALL_POKEMONS';
